### ISSUE TITLE
system_random_seed not exist in Julia Arcade Learning Environment

### ISSUE THREAD

**Issue by allenanie** [JuliaReinforcementLearning/ArcadeLearningEnvironment.jl#18]
Hello,

I ran into an error in this ALE package (My Julia version is 1.8.5). The ALE package version is 0.6.0.

I tried to set system random seed but seems like I couldn't?

```julia
using ArcadeLearningEnvironment
ale = ALE_new()
setInt(ale, "system_random_seed", 4753849)
```

Then the error is:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  The key system_random_seed you are trying to set does not exist.
```

System random seed can be set in the Python version of the ALE package.

**Comment by findmyway** [comment]
Try `"random_seed"` instead of `"system_random_seed"`?

**Comment by bhatiaabhinav** [comment]
Yep, that worked!
